### PR TITLE
RA-1000: Automatically pull translations

### PR DESCRIPTION
**Pull request by hpardess**
I have added the list of languages that has translation for openmrs-module-allergyapi in transifex.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@hpardess could these be of any use without creating the actual message properties files in the module?

You could also take a look at this: https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by hpardess** [comment]
@dkayiwa : Please refer to this post https://talk.openmrs.org/t/how-to-add-new-language-to-openmrs-2x/11008/4
As @djazayeri mentioned that Transifex will take care of downloading the message properties files.

**Comment by dkayiwa** [comment]
@hpardess my understanding was that it takes care of downloading existing message properties files. But not creating those that do not exist. @djazayeri am i correct?

**Comment by dkayiwa** [comment]
@hpardess my understanding was that it takes care of downloading existing message properties files. But not creating those that do not exist. Correct?

**Comment by dkayiwa** [comment]
@hpardess are you still working on this?

**Comment by dkayiwa** [comment]
@hpardess ping me to reopen this when you have time again. 😊

**Pull request closed without merging**
